version: 2
jobs: 
  build:
    docker:
      - image: "circleci/buildpack-deps"
    steps:
      - checkout
      - run: 
          name: Where are we
          command: 'pwd; ls'
      - run: 
          name: Installing third party 
          command: 'apt update && apt install freglut3-dev cmake'
      - run:
          name: Build raytracer
          command: 'mkdir build; cd build; cmake ..; make'
